name: Build Website

# Controls when the workflow will run
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Let workflow be reusable
  workflow_call:
    inputs:
      upload-artifact:
        description: "Upload artifact to be used by other workflows"
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3

      # Configure NPM to cache dependencies
      - name: 📦 Setup Node.js and caching
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "npm"

      # Install deps and build
      - name: 🔨 Install and Build
        run: |
          npm i
          npm run build
        env:
          VITE_PROJECT_URL: ${{ inputs.VITE_PROJECT_URL }}
          VITE_PUBLIC_KEY: ${{ inputs.VITE_PUBLIC_KEY }}

      # Upload artifact if requested
      - name: ⬆️ Upload artifact
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: "dist"
